# Text Representation

Text representation in NLP means converting text into a numerical form that a machine learning model can understand and process.

## What is Embedding?

Embeddings in NLP is a technique where individual words are represented as real-valued vectors and captures inter-word semantics.


In this notebook, We going to intreduce 2 techniques for embedding. These techniques will be used for a machine learning models such as SVM, Random forest, ... ect.

<img src="https://drive.google.com/uc?export=view&id=1jd0u_sGppDKqBYbhtJfGxp14lnUWUTTw" width="900">

# 1- TF-IDF

<img src="https://drive.google.com/uc?export=view&id=1saSt0mMgOQ2ybbTms1lu_ruhUcBWkKzL" width="500">

TF-IDF stands for term frequency-inverse document frequency. It is a measure that discounts common words. Used in the fields of information retrieval (IR) and machine learning, that can quantify the importance of words in a document amongst a collection of documents (also known as a corpus).

### Components of TF-IDF

1. **TF (Term Frequency):**  
   Measures how frequently a term appears in a document.


$$ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$


2. **IDF (Inverse Document Frequency):**  
   Measures how important a term is across all documents. Words that appear in many documents get lower scores.

$$    \text{IDF}(t) = \log \left(\frac{\text{Number of all documents N}}{\text{Number of documents containing the term } t}\right) $$

<img src="https://drive.google.com/uc?export=view&id=1JqPILC8TTh3yDQZCSuPNXwm6ER5YeJFh" width="900">

In [5]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [7]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data) # returns sparce matrix

In [8]:
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

# Cosine similarity

In NLP, Cosine similarity is a metric used to measure how similar the documents are.


$$ \text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|} $$

Where:  
$ A \cdot B $  = dot product of vectors A and B  
$ \|A\| $ = magnitude (length) of vector A  
$ \|B\| $ =  magnitude (length) of vector B

#### Intuition

- If vectors point in the **same direction**, cosine similarity = **1** (maximum similarity).
- If vectors are **orthogonal (90° apart)**, cosine similarity = **0** (no similarity).

<img src="https://drive.google.com/uc?export=view&id=1b-o8CVfHBsjUGY_hXmxevU91gHidIuxO" width="900">

In [9]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [10]:
# Sample text data (replace with your own documents)

doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [11]:
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [12]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

,Data is the oil of the digital economy,Data is a new oil
Data is the oil of the digital economy,1.000000,0.327871
Data is a new oil,0.327871,1.000000

# 2- What is Word2vec?

Word2Vec consists of models for generating word embedding. These models are two-layer neural networks having one input layer, one hidden layer, and one output layer.

Word2Vec utilizes two architectures :
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**
<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">


Run this command in terminal to install
> pip install gensim

We will use fake and real news dataset to do our expirament. You can find the dataset here: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset?select=True.csv

In [13]:
import pandas as pd
import nltk
import numpy as np
import gensim

from nltk.tokenize import word_tokenize

In [19]:
df = pd.read_csv('True.csv', engine='python', on_bad_lines='skip') #fake-and-real-news-dataset-true.csv
df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [20]:
tokens = []

for i in df['text']:
    token = word_tokenize(i)
    tokens.append(token)

In [21]:
w2v = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

In [22]:
print("Cosine similarity between 'provide' and 'program' - Skip Gram : ",w2v.wv.similarity('provide', 'program'))

Cosine similarity between 'provide' and 'program' - Skip Gram :  0.6699392

In [23]:
print("words that similar to 'program' - Skip Gram : ",w2v.wv.most_similar('program'))

words that similar to 'program' - Skip Gram :  [('protection', 0.8437550663948059), ('surveillance', 0.8380537033081055), ('internet', 0.8287907838821411), ('Medicaid', 0.8177972435951233), ('international', 0.8143428564071655), ('enforcement', 0.8115182518959045), ('environmental', 0.8078413009643555), ('regulations', 0.8058000802993774), ('helps', 0.8033673167228699), ('Dodd-Frank', 0.8011311292648315)]

# Tasks

### Task 1: Cosine Similarity
Use the Cosine Similarity method to determine how similar the following sentences are.

'This is the first document.',  
'This document is the second document.',  
'And this is the third one.',  
'Is this the first document?'

In [27]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

documents = ['This is the first document.','This document is the second document.','And this is the third one.','Is this the first document?']

tfidf_vectorizer = TfidfVectorizer()
vector_matrix = tfidf_vectorizer.fit_transform(documents)

cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(
    cosine_similarity_matrix,
    index=documents,
    columns=documents
)

df_cosine

,This is the first document.,This document is the second document.,And this is the third one.,Is this the first document?
This is the first document.,1.000000,0.646926,0.307772,1.000000
This document is the second document.,0.646926,1.000000,0.225240,0.646926
And this is the third one.,0.307772,0.225240,1.000000,0.307772
Is this the first document?,1.000000,0.646926,0.307772,1.000000

### Task 2: TF-IDF
Use tf-idf method on the sentences below to determine the important words.

'data science is one of the most important fields of science',  
'this is one of the best data science courses',  
'data scientists analyze data'

In [28]:
documents = ['data science is one of the most important fields of science','this is one of the best data science courses','data scientists analyze data']

tfidf = TfidfVectorizer()

result = tfidf.fit_transform(documents)

df = pd.DataFrame(
    result.toarray(),
    columns=tfidf.get_feature_names_out()
)

df

,analyze,best,courses,data,fields,important,is,most,of,one,science,scientists,the,this
0,0.000000,0.000000,0.000000,0.189526,0.320895,0.320895,0.244049,0.320895,0.488098,0.244049,0.488098,0.000000,0.244049,0.000000
1,0.000000,0.400294,0.400294,0.236420,0.000000,0.000000,0.304434,0.000000,0.304434,0.304434,0.304434,0.000000,0.304434,0.400294
2,0.542701,0.000000,0.000000,0.641055,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.542701,0.000000,0.000000

## Word2vec

### Task 3:

Download the Simpsons dataset **(simpsons_script_lines.csv)** and apply the preprocessing procedure.  
Use the **'spoken_words'** column.
```
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text
```
Create a skip gram Word2Vec model as below.
```
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

In [29]:
nltk.download('punkt')
nltk.download('punkt_tab')

# Load dataset
df = pd.read_csv('simpsons_script_lines.csv')

# Remove rows with missing spoken_words
df = df.dropna(subset=['spoken_words'])

# Clean text
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text

df['spoken_words'] = df['spoken_words'].apply(clean_text)

# Tokenization
tokens = []

for text in df['spoken_words']:
    token = word_tokenize(text)
    tokens.append(token)

# Build Skip-Gram Word2Vec model
Skip_gram_model = gensim.models.Word2Vec(tokens,min_count=1,vector_size=100,window=5,sg=1)

[nltk_data] Downloading package punkt to
[nltk_data]     /home/785fef4b-3249-4cb3-a1f5-
[nltk_data]     273c94d2b013/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/785fef4b-3249-4cb3-a1f5-
[nltk_data]     273c94d2b013/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

### Task 4

Use: wv.most_similar() method to :

1.	Find the words similar to “homer”.

2.	Find the words similar to “marge”.

3. Find the words similar to “bart”

In [30]:
print("Most similar to Homer:")
print(Skip_gram_model.wv.most_similar('homer'))

print("Most similar to Marge:")
print(Skip_gram_model.wv.most_similar('marge'))

print("Most similar to Bart:")
print(Skip_gram_model.wv.most_similar('bart'))

Most similar to Homer:
[('abe', 0.8784657716751099), ('marge', 0.8751319646835327), ('grampa', 0.8322471976280212), ('mister', 0.8256444931030273), ('jessica', 0.8236198425292969), ('eliza', 0.8198415637016296), ('ned', 0.8177187442779541), ('sweetheart', 0.8160319924354553), ('bart', 0.8158167004585266), ('waylon', 0.810573935508728)]
Most similar to Marge:
[('homer', 0.8751320242881775), ('abe', 0.8511826992034912), ('sweetheart', 0.8275133967399597), ('midge', 0.8207690715789795), ('becky', 0.8185404539108276), ('lisa', 0.8172730207443237), ('maude', 0.816328763961792), ('jessica', 0.8108956217765808), ('apu', 0.8098319172859192), ('allison', 0.8077125549316406)]
Most similar to Bart:
[('lisa', 0.8726806044578552), ('milhouse', 0.8702911734580994), ('jessica', 0.8476583957672119), ('grampa', 0.8340630531311035), ('eliza', 0.8203738331794739), ('sweetheart', 0.8196960687637329), ('allison', 0.8185708522796631), ('luann', 0.8181606531143188), ('laddie', 0.8158754706382751), ('homer', 0.8158167600631714)]

### Task 5

Use the wv.doesnt_match() method to :

1.	Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list.

3.	Find the odd one among "nelson", "bart", and "milhouse".

4.	Find the odd one among ‘homer', 'patty', and ‘selma'.

*Hint: You need to pass the strings as List*

In [31]:
print("Odd word in ['jimbo', 'milhouse', 'kearney']:")
print(Skip_gram_model.wv.doesnt_match(['jimbo', 'milhouse', 'kearney']))

print("Odd word in ['nelson', 'bart', 'milhouse']:")
print(Skip_gram_model.wv.doesnt_match(['nelson', 'bart', 'milhouse']))

print("Odd word in ['homer', 'patty', 'selma']:")
print(Skip_gram_model.wv.doesnt_match(['homer', 'patty', 'selma']))

Odd word in ['jimbo', 'milhouse', 'kearney']:
milhouse
Odd word in ['nelson', 'bart', 'milhouse']:
nelson
Odd word in ['homer', 'patty', 'selma']:
homer